### ISSUE TITLE
Having issues trying to write an ebuild for Bitwig 4.0.1

### ISSUE THREAD

**Issue by KevinThomas0** [gentoo-audio/audio-overlay#474]
Long story short, I run into this error shortly after running Bitwig:
```
[2021-07-19 13:08:30.811 float-engine-communication error] Error launching or running the engine process: Execution failed (Exit value: -559038737. Caused by java.io.IOException: Cannot run program "/opt/bitwig-studio/bin/BitwigAudioEngine-X64-AVX2" (in directory "/home/kevin/.BitwigStudio"): error=13, Permission denied)
```

Then, after trying to load a project I get this error, causing the program to crash:
```
[2021-07-22 09:07:52.650 float-main-app fatal] Application crashing in subsystem Uncaught Exception:
	java.lang.NullPointerException: Cannot invoke "String.length()" because "this.JNa" is null
	at com.bitwig.base.json.parser.tkn.Fep(SourceFile:36)
	at com.bitwig.base.json.parser.jqx.Fep(SourceFile:52)
	at com.bitwig.base.json.parser.CxV.Fep(SourceFile:521)
	at com.bitwig.base.json.parser.CxV.Fep(SourceFile:502)
	at com.bitwig.base.json.parser.RgI.Fep(SourceFile:83)
	at com.bitwig.base.json.parser.RgI.Fep(SourceFile:66)
	at com.bitwig.base.json.parser.RgI.Fep(SourceFile:57)
	at bWk.Fep(SourceFile:74)
	at bWf.TuP(SourceFile:231)
	at bWg.run(SourceFile:222)
	at java.base/java.util.TimerThread.mainLoop(Unknown Source)
	at java.base/java.util.TimerThread.run(Unknown Source)
```

After doing some debugging, I believe the problem lies with the libs in /opt/bitwig-studio/lib/jre/lib
and maybe the bins in /opt/bitwig-studio/lib/jre/bin as well too. The reason I believe this is because
when I download the .deb file manually and run Bitwig from the extracted files, it works fine. I did a diff
check on the manually downloaded files and the files installed by the ebuild and I get these differences:
```
Files bitwig-studio/bin/BitwigStudio and /opt/bitwig-studio/bin/BitwigStudio differ
Files bitwig-studio/lib/jre/bin/java and /opt/bitwig-studio/lib/jre/bin/java differ
Files bitwig-studio/lib/jre/bin/jrunscript and /opt/bitwig-studio/lib/jre/bin/jrunscript differ
Files bitwig-studio/lib/jre/bin/keytool and /opt/bitwig-studio/lib/jre/bin/keytool differ
Files bitwig-studio/lib/jre/lib/jexec and /opt/bitwig-studio/lib/jre/lib/jexec differ
Files bitwig-studio/lib/jre/lib/jspawnhelper and /opt/bitwig-studio/lib/jre/lib/jspawnhelper differ
Files bitwig-studio/lib/jre/lib/libawt_headless.so and /opt/bitwig-studio/lib/jre/lib/libawt_headless.so differ
Files bitwig-studio/lib/jre/lib/libawt.so and /opt/bitwig-studio/lib/jre/lib/libawt.so differ
Files bitwig-studio/lib/jre/lib/libawt_xawt.so and /opt/bitwig-studio/lib/jre/lib/libawt_xawt.so differ
Files bitwig-studio/lib/jre/lib/libdt_socket.so and /opt/bitwig-studio/lib/jre/lib/libdt_socket.so differ
Files bitwig-studio/lib/jre/lib/libfontmanager.so and /opt/bitwig-studio/lib/jre/lib/libfontmanager.so differ
Files bitwig-studio/lib/jre/lib/libharfbuzz.so and /opt/bitwig-studio/lib/jre/lib/libharfbuzz.so differ
Files bitwig-studio/lib/jre/lib/libj2gss.so and /opt/bitwig-studio/lib/jre/lib/libj2gss.so differ
Files bitwig-studio/lib/jre/lib/libjavajpeg.so and /opt/bitwig-studio/lib/jre/lib/libjavajpeg.so differ
Files bitwig-studio/lib/jre/lib/libjava.so and /opt/bitwig-studio/lib/jre/lib/libjava.so differ
Files bitwig-studio/lib/jre/lib/libjawt.so and /opt/bitwig-studio/lib/jre/lib/libjawt.so differ
Files bitwig-studio/lib/jre/lib/libjdwp.so and /opt/bitwig-studio/lib/jre/lib/libjdwp.so differ
Files bitwig-studio/lib/jre/lib/libjimage.so and /opt/bitwig-studio/lib/jre/lib/libjimage.so differ
Files bitwig-studio/lib/jre/lib/libjli.so and /opt/bitwig-studio/lib/jre/lib/libjli.so differ
Files bitwig-studio/lib/jre/lib/libjsig.so and /opt/bitwig-studio/lib/jre/lib/libjsig.so differ
Files bitwig-studio/lib/jre/lib/libjsound.so and /opt/bitwig-studio/lib/jre/lib/libjsound.so differ
Files bitwig-studio/lib/jre/lib/liblcms.so and /opt/bitwig-studio/lib/jre/lib/liblcms.so differ
Files bitwig-studio/lib/jre/lib/libmanagement.so and /opt/bitwig-studio/lib/jre/lib/libmanagement.so differ
Files bitwig-studio/lib/jre/lib/libmlib_image.so and /opt/bitwig-studio/lib/jre/lib/libmlib_image.so differ
Files bitwig-studio/lib/jre/lib/libnet.so and /opt/bitwig-studio/lib/jre/lib/libnet.so differ
Files bitwig-studio/lib/jre/lib/libnio.so and /opt/bitwig-studio/lib/jre/lib/libnio.so differ
Files bitwig-studio/lib/jre/lib/libprefs.so and /opt/bitwig-studio/lib/jre/lib/libprefs.so differ
Files bitwig-studio/lib/jre/lib/libsplashscreen.so and /opt/bitwig-studio/lib/jre/lib/libsplashscreen.so differ
Files bitwig-studio/lib/jre/lib/libverify.so and /opt/bitwig-studio/lib/jre/lib/libverify.so differ
Files bitwig-studio/lib/jre/lib/libzip.so and /opt/bitwig-studio/lib/jre/lib/libzip.so differ
Files bitwig-studio/lib/jre/lib/server/libjsig.so and /opt/bitwig-studio/lib/jre/lib/server/libjsig.so differ
Files bitwig-studio/lib/jre/lib/server/libjvm.so and /opt/bitwig-studio/lib/jre/lib/server/libjvm.so differ
```

To do some extra confirmation, I installed bitwig from my ebuild, deleted the /opt/bitwig-studio/lib/jre
directory, and then copied that same directory from the .deb file I manually downloaded. When I do that,
the program runs fine.

So that's why I think something is going wrong with these libs, but I'm pretty new to Gentoo packaging
so I was wondering if anyone had any insight as to how I could fix this?

Here is my ebuild for reference: https://github.com/KevinThomas0/audio-overlay/blob/bitwig-studio-4.0.1/media-sound/bitwig-studio/bitwig-studio-4.0.1.ebuild

**Comment by simonvanderveldt** [comment]
Thanks for the report. I can reproduce this/get the same error.

Both of these errors are very strange. I don't see a reason why bitwig would say permission denied for anyting in `/opt/bitwig-studio/bin`, everything is world readable. Maybe it's doing something crazy like trying to change files there?
You try running strace and see if it shows you what it's trying to do.

The second also seems pretty strange. Are you sure it works with the ebuild installed with just `/opt/bitwig-studio/lib/jre` replaced with the contents from the deb? I can't reproduce this, I still get the same error when doing this.

Bitwig itself seems to run fine despite this though?

**Comment by KevinThomas0** [comment]
> The second also seems pretty strange. Are you sure it works with the ebuild installed with just `/opt/bitwig-studio/lib/jre` replaced with the contents from the deb? I can't reproduce this, I still get the same error when doing this.

Interesting. Yeah the error goes away for me when I do that, here is my log after deleting the jre folder generated from the ebuild and replacing it with the folder from the the .deb:
```
$ ./bitwig-studio
About to start the following process:  /opt/bitwig-studio/bin/show-splash-gtk /opt/bitwig-studio/resources/splash-bitwig-studio.png
About to start the following process:  /opt/bitwig-studio/bin/BitwigStudio -cp /opt/bitwig-studio/bin/bitwig.jar:/opt/bitwig-studio/lib/cp:/opt/bitwig-studio/bin/libs.jar:/opt/bitwig-studio/bin/lwjgl.jar -Dorg.sqlite.lib.path=/opt/bitwig-studio/lib/bitwig-studio -XX:+UseZGC -Xms300m -XX:SoftMaxHeapSize=2048m -Xmx3072m -Djava.io.tmpdir=/tmp/bitwig-kevin -DinstallationRoot=/opt/bitwig-studio -DsplashPid=1007 -Djava.awt.headless=true -XX:ErrorFile=/home/kevin/.BitwigStudio/bitwig-studio-jvm-crash.log com.bitwig.flt.app.BitwigStudioMain

(show-splash-gtk:1007): Gtk-WARNING **: 19:42:15.551: Theme parsing error: gtk.css:6360:24: 'none' is not a valid color name
Using log directory /home/kevin/.BitwigStudio/log
[2021-07-25 19:42:15.703 float-main-app info] Starting application version 4.0.1 revision ba6620e32249635c4199fe76ffc20ed2b675aae6
[2021-07-25 19:42:15.713 float-main-app info] Using Java version 16 from Oracle Corporation installed at /opt/bitwig-studio/lib/jre
[2021-07-25 19:42:15.713 float-main-app info] Starting with arguments
[2021-07-25 19:42:17.883 gui-toolkit-core info] Using locale en
[2021-07-25 19:42:18.305 float-telemetry info] Starting Telemetry
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Using overridden package repository location: "http://packs.bitwig.com/repository"
[2021-07-25 19:42:20.145 float-document-master info] Starting engine for New 1
[2021-07-25 19:42:20.148 float-gui-widgets info] Connecting audio engine to project New 1
[2021-07-25 19:42:20.156 float-engine-communication info] Engine process successfully started
[2021-07-25 19:42:20.506 base-util info] Updating index /opt/bitwig-studio/Library/devices for phase devices: time=5.150533
[2021-07-25 19:42:20.507 base-util info] Updating index /opt/bitwig-studio/Library/modulators for phase devices: time=1.0745
[2021-07-25 19:42:20.511 base-util info] Updating index /opt/bitwig-studio/Library/modules for phase devices: time=3.48939
[2021-07-25 19:42:20.512 base-util info] Updating index /media/kevin/nvme/Bitwig Library for phase projects: time=0.431181
[2021-07-25 19:42:20.528 base-util info] Updating index /media/kevin/nvme/Bitwig Projects for phase projects: time=16.598352
[2021-07-25 19:42:20.529 base-util info] Updating index /media/kevin/nvme/Bitwig Library for phase audio: time=0.323588
[2021-07-25 19:42:20.636 base-util info] Updating index /media/kevin/nvme/BitwigStudio/Installed Bitwig Packs/1.0/Installed Bitwig Packs/1.0/samples for phase audio: time=107.21713
[2021-07-25 19:42:20.662 base-util info] Updating index /media/kevin/nvme/BitwigStudio/Installed Bitwig Packs/1.0/Installed Bitwig Packs/1.0/presets for phase packages: time=25.240248
[2021-07-25 19:42:20.664 base-util info] Updating index /media/kevin/nvme/BitwigStudio/Installed Bitwig Packs/1.0/Installed Bitwig Packs/1.0/wavetables for phase packages: time=1.613143
[2021-07-25 19:42:20.667 base-util info] Updating index /media/kevin/nvme/BitwigStudio/Installed Bitwig Packs/1.0/Installed Bitwig Packs/1.0/multi-samples for phase packages: time=2.728519
[2021-07-25 19:42:20.676 base-util info] Updating index /media/kevin/nvme/BitwigStudio/Installed Bitwig Packs/1.0/Installed Bitwig Packs/1.0/clips for phase packages: time=8.690988
[2021-07-25 19:42:20.676 base-util info] Updating index /media/kevin/nvme/BitwigStudio/Installed Bitwig Packs/1.0/Installed Bitwig Packs/1.0/templates for phase packages: time=0.301937
[2021-07-25 19:42:20.676 base-util info] Updating index /media/kevin/nvme/Bitwig Library for phase wavetable: time=0.183264
[2021-07-25 19:42:20.677 base-util info] Updating index /media/kevin/nvme/Bitwig Library for phase content: time=0.178155
[2021-07-25 19:42:20.677 base-util info] Updating index /media/kevin/nvme/Bitwig Library for phase plugin_presets: time=0.160893
[2021-07-25 19:42:20.757 float-engine-communication info] Engine connecting with sample rate 48000 and block size 256
[2021-07-25 19:42:20.810 float-document-master info] Engine connected to project New 1
```

> Bitwig itself seems to run fine despite this though? (I haven't tried any audio, just ran it)

For me, Bitwig will crash after about 30 seconds of just doing nothing, and it will crash instantly if I try to load a project.
