### ISSUE TITLE
media-plugins/bitrot: Bump PYTHON_COMPAT to py3.11

### ISSUE THREAD

**Issue by NexAdn** [gentoo-audio/audio-overlay#531]
Python 3.11 is becoming the default Python implementation in June 2023. Thus, this package should be tested against Python 3.11 and PYTHON_COMPAT should be bumped if the test was successful.

**Comment by NexAdn** [comment]
This plugin fails to configure due to an invalid wscript:

```
>>> Unpacking source...
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /var/cache/distfiles/git3-src/grejppi_bitrot.git/
 * Repository id: grejppi_bitrot.git
 * To override fetched repository properties, use:
 *   EGIT_OVERRIDE_REPO_GREJPPI_BITROT
 *   EGIT_OVERRIDE_BRANCH_GREJPPI_BITROT
 *   EGIT_OVERRIDE_COMMIT_GREJPPI_BITROT
 *   EGIT_OVERRIDE_COMMIT_DATE_GREJPPI_BITROT
 * 
 * Fetching https://github.com/grejppi/bitrot.git ...
git fetch https://github.com/grejppi/bitrot.git +HEAD:refs/git-r3/HEAD --depth 1
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 30 (delta 6), reused 19 (delta 3), pack-reused 0
Unpacking objects: 100% (30/30), 117.12 KiB | 2.21 MiB/s, done.
From https://github.com/grejppi/bitrot
 * [new ref]                    -> refs/git-r3/HEAD
git symbolic-ref refs/git-r3/media-plugins/bitrot/0/__main__ refs/git-r3/HEAD
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /var/cache/distfiles/git3-src/grejppi_DPF.git/
 * Repository id: grejppi_DPF.git
 * To override fetched repository properties, use:
 *   EGIT_OVERRIDE_REPO_GREJPPI_DPF
 *   EGIT_OVERRIDE_BRANCH_GREJPPI_DPF
 *   EGIT_OVERRIDE_COMMIT_GREJPPI_DPF
 *   EGIT_OVERRIDE_COMMIT_DATE_GREJPPI_DPF
 * 
 * Fetching https://github.com/grejppi/DPF.git ...
git fetch https://github.com/grejppi/DPF.git --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +refs/pull/*/head:refs/pull/* +HEAD:refs/git-r3/HEAD
remote: Enumerating objects: 6888, done.
remote: Total 6888 (delta 0), reused 0 (delta 0), pack-reused 6888
Receiving objects: 100% (6888/6888), 11.67 MiB | 3.80 MiB/s, done.
Resolving deltas: 100% (5832/5832), done.
From https://github.com/grejppi/DPF
 * [new branch]      append-manifest -> append-manifest
 * [new branch]      automatable     -> automatable
 * [new branch]      custom          -> custom
 * [new branch]      gh-pages        -> gh-pages
 * [new branch]      integer         -> integer
 * [new branch]      master          -> master
 * [new branch]      midi-input      -> midi-input
 * [new branch]      replaced-uri    -> replaced-uri
 * [new branch]      sample-rate     -> sample-rate
 * [new branch]      trigger         -> trigger
 * [new ref]                         -> refs/git-r3/HEAD
git update-ref --no-deref refs/git-r3/media-plugins/bitrot/0/DPF/__main__ 74aec5b6a2350805edd6ad7344a79966eb467fa9
 * Checking out https://github.com/grejppi/bitrot.git to /var/tmp/portage/media-plugins/bitrot-9999/work/bitrot-9999 ...
git checkout --quiet refs/git-r3/HEAD
GIT NEW branch -->
   repository:               https://github.com/grejppi/bitrot.git
   at the commit:            70534bce27dbbe4bb3d526877eca56f81538c827
 * Checking out https://github.com/grejppi/DPF.git to /var/tmp/portage/media-plugins/bitrot-9999/work/bitrot-9999/DPF ...
git checkout --quiet 74aec5b6a2350805edd6ad7344a79966eb467fa9
GIT NEW branch -->
   repository:               https://github.com/grejppi/DPF.git
   at the commit:            74aec5b6a2350805edd6ad7344a79966eb467fa9
>>> Source unpacked in /var/tmp/portage/media-plugins/bitrot-9999/work
>>> Preparing source in /var/tmp/portage/media-plugins/bitrot-9999/work/bitrot-9999 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/media-plugins/bitrot-9999/work/bitrot-9999 ...
'PYTHONHASHSEED=1' 'CCFLAGS=-march=native -O2 -pipe -Wodr -frecord-gcc-switches' 'LINKFLAGS=-march=native -O2 -pipe -Wodr -frecord-gcc-switches -march=native -O2 -pipe -Wodr -Wl,-O1 -Wl,--defsym=__gentoo_check_ldflags__=0' 'PKGCONFIG=x86_64-pc-linux-gnu-pkg-config' '/var/tmp/portage/media-plugins/bitrot-9999/work/bitrot-9999/waf' '--jobs=1' '--prefix=/usr' 'configure'
Waf: The wscript in '/var/tmp/portage/media-plugins/bitrot-9999/work/bitrot-9999' is unreadable
Traceback (most recent call last):
  File "/var/tmp/portage/media-plugins/bitrot-9999/work/bitrot-9999/.waf3-2.0.12-6cd57ca9068ebdd4dc6caef5723653c7/waflib/Scripting.py", line 102, in waf_entry_point
    set_main_module(wscript)
  File "/var/tmp/portage/media-plugins/bitrot-9999/work/bitrot-9999/.waf3-2.0.12-6cd57ca9068ebdd4dc6caef5723653c7/waflib/Scripting.py", line 142, in set_main_module
    Context.g_module=Context.load_module(file_path)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/media-plugins/bitrot-9999/work/bitrot-9999/.waf3-2.0.12-6cd57ca9068ebdd4dc6caef5723653c7/waflib/Context.py", line 349, in load_module
    code=Utils.readf(path,m='rU',encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/media-plugins/bitrot-9999/work/bitrot-9999/.waf3-2.0.12-6cd57ca9068ebdd4dc6caef5723653c7/waflib/Utils.py", line 141, in readf
    with open(fname,m)as f:
         ^^^^^^^^^^^^^
ValueError: invalid mode: 'rUb'
 * ERROR: media-plugins/bitrot-9999::audio-overlay failed (configure phase):
 *   configure failed
 * 
 * Call stack:
 *     ebuild.sh, line  136:  Called src_configure
 *   environment, line 2597:  Called waf-utils_src_configure
 *   environment, line 3453:  Called die
 * The specific snippet of code:
 *       env "${CMD[@]}" || die "configure failed"
 * 
 * If you need support, post the output of `emerge --info '=media-plugins/bitrot-9999::audio-overlay'`,
 * the complete build log and the output of `emerge -pqv '=media-plugins/bitrot-9999::audio-overlay'`.
 * The complete build log is located at '/var/tmp/portage/media-plugins/bitrot-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/media-plugins/bitrot-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/media-plugins/bitrot-9999/work/bitrot-9999'
 * S: '/var/tmp/portage/media-plugins/bitrot-9999/work/bitrot-9999'

 * Messages for package media-plugins/bitrot-9999:

 * ERROR: media-plugins/bitrot-9999::audio-overlay failed (configure phase):
 *   configure failed
 * 
 * Call stack:
 *     ebuild.sh, line  136:  Called src_configure
 *   environment, line 2597:  Called waf-utils_src_configure
 *   environment, line 3453:  Called die
 * The specific snippet of code:
 *       env "${CMD[@]}" || die "configure failed"
 * 
 * If you need support, post the output of `emerge --info '=media-plugins/bitrot-9999::audio-overlay'`,
 * the complete build log and the output of `emerge -pqv '=media-plugins/bitrot-9999::audio-overlay'`.
 * The complete build log is located at '/var/tmp/portage/media-plugins/bitrot-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/media-plugins/bitrot-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/media-plugins/bitrot-9999/work/bitrot-9999'
 * S: '/var/tmp/portage/media-plugins/bitrot-9999/work/bitrot-9999'
```

**Comment by NexAdn** [comment]
Issue created upstream. Python 3.10 seems to work, so we can use that for now to mitigate global scope failures.

**Comment by NexAdn** [comment]
Upstream has seen no activity in years. Since I don't have the resources to upstream all the changes needed for every waf package that needs bumping, I'll start masking for removal now.
